version: "3.9"

services:
  ssh1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ssh_container1
    ports:
      - "2221:22"
  
  ssh2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ssh_container2
    ports:
      - "2222:22"
  
  ssh3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ssh_container3
    ports:
      - "2223:22"
